### ISSUE TITLE
Incomplete requirements.txt for builder.py, and more

### ISSUE THREAD

**Issue by walkjivefly** [blocknetdx/exrproxy-env#145]
Using branch dev-autobuilder-pom
```
blockops@ops1:~/src/exrproxy-env$ pip3 install -r requirements.txt
Requirement already satisfied: jinja2 in /home/blockops/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.0.2)
...
blockops@ops1:~/src/exrproxy-env$ ./builder.py --help
Traceback (most recent call last):
  File "./builder.py", line 2, in <module>
    from autobuild.utils import *
  File "/home/blockops/src/exrproxy-env/autobuild/utils/__init__.py", line 4, in <module>
    from PyInquirer import style_from_dict, Token, prompt, Separator
ModuleNotFoundError: No module named 'PyInquirer'
```
After installing it, builder.py next failed with
```
blockops@ops1:~/src/exrproxy-env$ ./builder.py

- EXRPROXY-ENV - BUILDER

Loading File: autobuild/sources.yaml
? Press enter for 35USD tier1 amount or type a new price:  
? Press enter for 200USD tier2 amount or type a new price:  
? Press enter for 20% aBlock discount or type a new discount:  
? Press enter for 20% aaBlock discount or type a new discount:  
? What chains do you wish to support?  [SYS]
? What EVM chains do you wish to support?  [AVAX]
? Press enter to use AVAX internally or type external IP Address:  
? Do you wish to configure HYDRA?  Yes
? Select EVM chains to attach HYDRA to:  [AVAX]
? Do you wish to configure XQUERY?  Yes
? Select EVM chains to attach XQUERY to:  [AVAX]
? Select which indices you want for AVAX:  [PANGOLIN]
? Press enter to save config as 14-02-2022-15:36 or enter name:  
Traceback (most recent call last):
  File "./builder.py", line 104, in <module>
    print(write_yaml_file(f'inputs_yaml/{now}.yaml',input_template))
  File "/home/blockops/src/exrproxy-env/autobuild/utils/autoconfig.py", line 19, in write_yaml_file
    with open(filename, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'inputs_yaml/14-02-2022-15:36.yaml'
```

**Comment by walkjivefly** [comment]
Oh, and builder.py could do with having execute permission set.
