### ISSUE TITLE
builder.py crashes when docker not installed

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#150]
In uninstalled docker completely from my VPS2. Then I ran this:
```
conan@VPS2:~/exrproxy-env$ python3 builder.py 

- EXRPROXY-ENV - BUILDER

Checking docker daemon...
Docker not installed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/home/conan/.local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by pom11** [comment]
solved. pls try again

**Comment by ConanMishler** [comment]
Some progress, but still not quite there...
```
conan@VPS2:~/exrproxy-env$ python3 builder.py 

- EXRPROXY-ENV - BUILDER

Checking docker daemon...
Docker not installed
? Do you want to install docker?  Yes
conan@VPS2:~/exrproxy-env$ [sudo] password for conan: 
sudo: unable to read password: Input/output error
[sudo] password for conan: 
sudo: unable to read password: Input/output error
[sudo] password for conan: 
sudo: unable to read password: Input/output error
(23) Failed writing body
```
It seems like it's not waiting for me to input my sudo password.
